### ISSUE TITLE
How to express intersection types?

### ISSUE THREAD

**Issue by Geordi7** [badrap/valita#11]
A quick vanilla example:

```typescript
type T1<F> = {field: F}
type T2 = {label: 'stringy'}
type X = T1<string> & T2
```

I want to do this in valita... I expected this to work:

```typescript
import {Type, Infer, object, string, literal} from '@badrap/valita';
const T1 = <FT extends Type>(F: FT) => object({field: F});
const T1s = T1(string());
const T2 = object({label: literal('stringy')});
const X = T1s.chain(T2.parse);
type X = Infer<typeof T1s> & Infer<typeof T2>;
```
(Note: in this example the `X` type is correctly inferred)

but tsc doesn't accept `.chain(T2.parse)` maybe there should be a `.isect(T2)` that just accepts the type?

**Comment by marvinhagemeister** [comment]
As far as I can tell this goes a bit against the use case valita was designed for. The main idea behind this library is that you define your schema to validate data and can automatically derive types form that.

In the example posted it seems like the opposite is the case. It tries to express TS types and then somehow turn them into a schema.

**Comment by jviide** [comment]
Yeah, it's a bit tricky. We've avoided introducing intersection types, as we haven't figured out a way for them to work nicely (to some arbitrary definition of "nice") with transformed types. Let's assume there's a `v.intersection(...)` function for creating intersections. In such case we could do something like this:

```
const T1 = v.object({ field: v.string().map((x) => (y: string) => x === y });
const T2 = v.object({ field: v.string().map((x) => (z: string) => x === z });
const T = v.intersection(T1, T2);
```

Maybe somewhat contrived, but I think it gets the point across 🙂 What should the result of `T.parse({ field: "test" })` be?

AFAIK some other libraries solve this problem by first parsing the input with both `T1` and `T2` and then comparing the two results with a deep equality check and merge them if everything seems ok. It's a perfectly valid and pragmatic approach. However, in this case `T` would look fine on the type level, but won't ever parse anything succesfully at runtime as it'd be pretty hard to determine that the resulting functions are essentially the same.

If it's ok for you that `T2`'s overlapping field(s) overwrite `T1`'s overlapping fields then I recommend trying out `T1.extend(T2.shape)`.

`T1.chain(T2)` could work, and in fact we've been thinking about having something like that in the future. That approach would make the relation between overlapping object fields more explicit: overlapping fields get parsed with T1 first and the result then gets parsed with T2.

**Comment by Geordi7** [comment]
> If it's ok for you that `T2`'s overlapping field(s) overwrite `T1`'s overlapping fields then I recommend trying out `T1.extend(T2.shape)`

Thanks! This is a very workable solution as long as we are careful/intentional about the order.

In this example:
```typescript
const T1 = v.object({ field: v.string().map((x) => (y: string) => x === y });
const T2 = v.object({ field: v.string().map((x) => (z: string) => x === z });
const T = v.intersection(T1, T2);
```
I'm afraid I have a philosophical gripe, as I don't really think a validation function should transform the objects it's validating.

**Comment by jviide** [comment]
I agree with your philosophical gripe, and that's exactly why valita is described as "validation **&** parsing library" and the parsing method is called `parse` instead of `validate` (as well as paying homage to [Zod](https://github.com/colinhacks/zod) 🙂)

Valita does not mutate its inputs, instead it constructs new objects when necessary. For example the following always creates a new object as output (without modifying the input):

```ts
const t = v.object({ field: v.string().map((x) => `a${x}b` });
const input = { field: "test" };
const output = t.parse(input);
input.field;       // "test"
output.field;      // "atestb"
output === input;  // false
```

When Valita can determine that the input isn't transformed in any way then it avoids constructing new instances:

```ts
const t = v.object({ field: v.string() });
const input = { field: "test" };
const output = t.parse(input);
input.field;       // "test"
output.field;      // "test"
output === input;  // true
```

So, in effect you can do pure validation if you so wish.

However, Valita was originally constructed for our JSON-oriented APIs that can ingest things like IP addresses or base64 encoded binary data. In such cases it made sense to make IP validation _and_ normalization or base64 validation _and_ string-to-Buffer transformations atomic parts of the same pipeline (including error reporting).

```ts
const b64 = () => {
  return v
    .string()
    .assert((x) => isBase64(x), "expected a base64 encoded string")
    .map((x) => Buffer.from(x, "base64"));
};

// Then later...

const t = v.object({ data: b64().assert(isPNG, "expected PNG data") });
t.parse({ data: "ååååå" });
// Uncaught ValitaError: custom_error at .data (expected a base64 encoded string)
```
