### ISSUE TITLE
Recursive Types Cannot be Defined

### ISSUE THREAD

**Issue by Geordi7** [badrap/valita#13]
I might have a Typescript type like this:

```typescript
type T = string | T[]
```

But if I try to define this type in valita I cannot pass the identifier to its own instantiator:

```typescript
const T = v.union(v.string(), v.array(T)); // error: identifier used before it is defined
```

I mulled over this a bit, but I can't think of a smart way to implement it that doesn't involve somehow the union after it is instantiated, and then having to trick typescript into giving it a different type...

**Comment by Bubz43** [comment]
I think chaining off of unknown should let you do this. 

```ts
function recursive<R>(getSchema: () => Type<R>) {
  return unknown().chain((value) => {
    const schema = getSchema();
    try {
      return ok(schema.parse(value));
    } catch (error) {
      return err((error as ValitaError).message);
    }
  });
}

type T = string | T[];
const T: Type<T> = union(string(), array(recursive(() => T)));
```

**Comment by Geordi7** [comment]
That... really blew my mind

**Comment by Geordi7** [comment]
Having used this a bit, I propose the following:

Add a `lazy()` type constructor to valita, which behaves like Bubz43's `recursive` function. Giving us idiomatic recursion and references between types that would otherwise have issues with order of instantiation:

```typescript
const A = object({
    a: string(),
    b: lazy(() => B).optional(),
});

const B = object({
    b: string(),
    a: lazy(() => A).optional(),
});
```

**Comment by jviide** [comment]
Good discussion! Yes, recursive types are indeed something that we ourselves have needed for some time now. So I added `lazy` to the library, it works quite similarly to @Bubz43's suggestion with some additional guardrails:

```ts
type T = string | T[];
const t: v.Type<T> = v.lazy(() => v.union(v.string(), v.array(t)));
```

The main problem here was trying to solve was the following scenario:

```ts
type T = string | T[];
const t: v.Type<T> = v.lazy(() => v.union(v.string(), v.array(t)).optional());

// Uh oh, t's optionality is erased:
const o = v.object({ t });
type X = v.Infer<typeof o>; // { t: T }, should be { t?: T }
```

So I took some drastic measures and restricted where `.optional()` types can be used! 🙂 For example, you now can't return an optional from `lazy`, so this is a type error:

```ts
const t: v.Type<T> = v.lazy(() => v.union(v.string(), v.array(t)).optional());
```

As is this:

```ts
const t: v.Type<T> = v.lazy(() => v.union(v.string(), v.array(t))).optional();
```

The most common usecase for `.optional()` is still supported:

```ts
type T = string | T[];
const t: v.Type<T> = v.lazy(() => v.union(v.string(), v.array(t)));

const o = t.object({
  x: t.optional()
});
```

I believe this a pretty good tradeoff between expressivity and providing safe guardrails against accidents. This _is_ a backwards incompatible change, for which I apologize. Looking at the only public repository using Valita, @Bubz43's https://github.com/Bubz43/ep2e, it seems that no changes are needed there at least 🙂

**Comment by jviide** [comment]
Version v0.0.18 is now published, containing `v.lazy` 👍

**Comment by Bubz43** [comment]
I'm using Valita quite heavily in a not yet public rework of that project with plenty of v.optionals and I didn't have to change anything, so it shouldn't be too breaking.

**Comment by jviide** [comment]
Awesome 👍 

Oh, and for completeness' sake we should mention Zod's [`lazy`](https://github.com/colinhacks/zod#recursive-types) here as well. `v.lazy` is named after it (and @Geordi7's suggestion) and behaves almost similarly. Thanks, Zod ❤️
