### ISSUE TITLE
v.lazy() causes error

### ISSUE THREAD

**Issue by Geordi7** [badrap/valita#22]
Example:

```typescript
try {
    type P = {p?: P};
    const P: v.Type<P> = v.object({
        p: v.lazy(() => P).optional(),
    })
    
    P.parse({p: {}});
} catch (e) {
    console.error(e);
}
```

This causes a `RangeError: Maximum call stack size exceeded`

It gets stuck in an infinite recursion calling `genFunc()` on itself

**Comment by jviide** [comment]
Thanks for the report! New version v0.0.22 containing the fix has now been published.
