### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by timonson** [badrap/valita#25]
Hi guys, is there any interest to support deno?

I am already using `valita` with Deno and it is completely compatible. The only issue is that I have to use a bundled version and import it from a CDN like https://cdn.jsdelivr.net/gh/badrap/valita@d5d0125c467fb307addb9cc2badd098bfc66b834/src/index.ts .

Maybe you could implement *webhooks* pointing to the `index.ts` file which would publish the new releases on https://deno.land/x. automatically You can find more about it on Deno's website [here](https://deno.land/x#info).

Thanks!

**Comment by jviide** [comment]
Thanks, that's a good idea! The src/ directory is now published at https://deno.land/x/valita
