### ISSUE TITLE
Exporting AbstractType

### ISSUE THREAD

**Issue by threema-danilo** [badrap/valita#26]
I currently have some HTTP request functions with a signature similar to this:

```ts
private async _request<TSchema extends v.ObjectType>(
    requestPath: string,
    schema: TSchema,
): Promise<v.Infer<TSchema>> {
```

This is really nice, because I can do generic validation of a JSON response body. However, it only works with object types, not with union types.

The type that `v.Infer` requires is `T extends AbstractType`. However, I cannot write that into my function signature because `AbstractType` isn't exported. Would it be possible to export `AbstractType`?

**Comment by jviide** [comment]
You can use `v.Type`:

```ts
private async _request<TSchema extends v.Type>(
    requestPath: string,
    schema: TSchema,
): Promise<v.Infer<TSchema>> {
```

**Comment by threema-danilo** [comment]
Thank you @jviide, that works! 🙂
