### ISSUE TITLE
Issue with generics

### ISSUE THREAD

**Issue by reinismu** [badrap/valita#3]
One thing I would like to do is create a generic parsing method for network requests. It would take in shape and return `Infer`. Currently it doesn't work fully.

```
const fetchAndValidate = async <A extends Type>(url: string, responseShape: A): Promise<Infer<A>> => {
    const result = await fetch(url);
    return responseShape.parse(result); // Type 'unknown' is not assignable to type 'SomethingOutputOf<A>'
}
```

Am I doing something wrong or there is something off with types?

**Comment by jviide** [comment]
That does seem like an oversight indeed. I modified `Type#parse`'s return type and published v0.0.12 - does the new version solve your problem?

**Comment by reinismu** [comment]
Awesome! That solved it :)

**Comment by jviide** [comment]
Sweet! Closing this issue 👍
