### ISSUE TITLE
Extending objects

### ISSUE THREAD

**Issue by reinismu** [badrap/valita#4]
Zod had `.extend()` method on most types.

I can use `v.object({ ...BaseType, <Wriet my stuff>})`

It works fine in all cases except when I have `v.object({}).assert(...)`. Then I can't get shape out of it. I guess even if I would get it, I would love my assert. Any ideas on how I could improve this?

**Comment by jviide** [comment]
What's your specific scenario - does the `.assert(...)` need to access the whole object, or would something like `v.object({ a: v.string().assert(...) })` suffice?

**Comment by reinismu** [comment]
In my case, it needs to access the whole object. Or specifically 2 fields. Need to make sure that they both are defined or none.

```
export const Turn = v.object({
    ...RoundBase.shape,
    name: v.literal('turn'),
    actions: v.array(DeliberateActionPostFlop),

    communityCard: OptionalPlayingCard,
    communityCardTimestamp: v.union(v.null(), v.number()).optional(),
}).assert(({ communityCard, communityCardTimestamp }) => {
    if (!communityCard) {
        return true;
    }

    return !!communityCardTimestamp;
}, 'Community card timestamp must be set');
```

Later I would like to do `v.object({...Turn, <more fields>})`

**Comment by reinismu** [comment]
Super! That is very nice 😊
