### ISSUE TITLE
Helper methods

### ISSUE THREAD

**Issue by reinismu** [badrap/valita#5]
Zod and MyZod have many helper methods `.int()` `.max(10)` `.pattern()` `.safeParse()` etc.

How do you look at these?

Currently it is possible to solve this all with `.assert()`

**Comment by jviide** [comment]
I'd like to keep the base functionality as compact as possible and make using tree-shakable helper collections like [validator.js](https://github.com/validatorjs/validator.js) relatively easy. Everyone seems to need just a slightly different set of helpers, and supporting all those use cases with builtins would likely make the maintenance burden prohibitive for us 🙂

For example `.max` could be handled like this:

```ts
const max = (maxNumber: number) => {
  return (value: number) => {
    if (value > maxNumber) {
      return t.err(`expected a number <= ${maxNumber}`);
    }
    return t.ok(value);
  };
};

const n = v.number().chain(max(10));
```

Or email validation & normalization like this using [validator.js](https://github.com/validatorjs/validator.js):

```ts
import isEmail from "validator/lib/isEmail";
import normalizeEmail from "validator/lib/normalizeEmail";

const email = v.string().assert(isEmail, "expected a valid email").map(normalizeEmail);
```

That said, something like `.safeParse` is definitely on the radar.

**Comment by jviide** [comment]
Version v0.0.18 is now published, containing the new `.try` method that works somewhat like `safeParse` but returns the following type:

```ts
type ValitaResult<V> =
  | Readonly<{
      ok: true;
      value: V;
    }>
  | Readonly<{
      ok: false;
      message: string; // Similar to ValitaError.message
      issues: readonly Issue[]; // Similar to ValitaError.issue
      throw(): never; // Throws a ValitaError containing the same info
    }>;
```

I chose to not use the type `{ ok: false, error: ValitaError }` for the failure types, as AFAIK creating Error instances is quite a bit slower than "regular" objects (I may be wrong, pinging @developit & @marvinhagemeister 😛) so maybe it's best to avoid that whenever possible.

**Comment by marvinhagemeister** [comment]
> I may be wrong, pinging @developit & @marvinhagemeister 😛) so maybe it's best to avoid that whenever possible.

Creating `Error` objects is slightly slower from my experience due to the overhead of collecting stack frames 👍
