### ISSUE TITLE
Undefined error message in Firefox

### ISSUE THREAD

**Issue by marvinhagemeister** [badrap/valita#7]
For some reason the error message in Firefox is `undefined` instead of showing the path to the key where the validation error occurred. This only happens when the error is logged to console. If we inspect the error object manually we can see that all properties are present as they should be.

Reproduction: https://i6nu3.csb.app/

<img width="429" alt="Screenshot 2021-05-11 at 16 48 06" src="https://user-images.githubusercontent.com/1062408/117836053-ab054100-b278-11eb-8e75-eb5a5dbecca9.png">

**Comment by marvinhagemeister** [comment]
All hints point to this being a bug in Firefox. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1710694

**Comment by jviide** [comment]
Commit 21743d6b16af3b27031ac228c7fe029cd3190674 fixes the issue by not formatting `ValitaError.message` lazily. Instead the error message is created up-front when the error instance itself is created.

If the Firefox issue gets resolved then we can move back to the lazy approach :)

**Comment by jviide** [comment]
Turns out that this was actually caused by 2 bugs in Firefox, and they're now fixed in the current beta: https://bugzilla.mozilla.org/show_bug.cgi?id=1710694#c8

> The bug is verified as fixed on Beta 90.0b4, across platforms: Win 10 x64, macOS 10.15 and Ubuntu 18.04 x64.

Huge thanks to @marvinhagemeister and the FF folks for investigating this further \o/ Let's bring back the lazy messages after FF90 comes out.
